package LessonObjects;

public enum Major {
	PETROLEUM_ENGINEERING, GEOLOGY_AND_EXPLORATION_OF_MINERAL_RESOURCES, INFORMATION_SYSTEMS,
	AUTOMATION_AND_CONTROL, COMPUTER_SYSTEMS_AND_SOFTWARE, CHEMICAL_TECHNOLOGIES_OF_ORGANIC_SUBSTANCES,
	MATHEMATICS_AND_ECONOMICS, ECONOMICS, FINANCE, MANAGEMENT, ACCOUNTING_AND_AUDITING, PROJECT_MANAGEMENT,
	SOCIETY_AND_TECHNOLOGY, MARKETING, MATHEMATICS_AND_COMPUTER, MATHEMATICS_AND_COMPUTER_MODELING,
	MBA_OIL_AND_GAS, MBA_FINANCE, MBA_LEADERSHIP, MBA_IN_MANAGING_THE_GREEN_ECONOMY, MBA_IN_IT_MANAGEMENT,
	MS_IN_FINANCIAL_ANALYSIS, EMBA_OIL_AND_GAS, CHEMICAL_TECHNOLOGY_OF_INORGANIC_SUBSTANCES,
	PETRO_CHEMISTRY, NANOTECHNOLOGY
}
